# Generated by cucumber-sinatra. (2013-12-03 12:11:29 +0000)

ENV['RACK_ENV'] = 'test'
ENV['METRICS_API_USERNAME'] = 'sam'
ENV['METRICS_API_PASSWORD'] = 'insulin'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/pancreas-api.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'cucumber/api_steps'
require 'database_cleaner'
require 'database_cleaner/cucumber'

require 'coveralls'
Coveralls.wear!

DatabaseCleaner.strategy = :truncation

Capybara.app = PancreasApi

class PancreasApiWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
  
  def app
    PancreasApi
  end
end

World do
  PancreasApiWorld.new
end
