Feature: Diabetes time ranges

  Background:
    Given I send and accept JSON
    And there is a metric in the database with the name "humalog"
    And it has a datetime of "2014-01-14T12:25:30+00:00"
    And it has a category of "Lunch"
    And it has a value of "7.5"
    And there is a metric in the database with the name "humalog"
    And it has a datetime of "2014-01-14T18:47:19+00:00"
    And it has a category of "Dinner"
    And it has a value of "6.0"
    And there is a metric in the database with the name "humalog"
    And it has a datetime of "2014-01-15T07:24:04+00:00"
    And it has a category of "Breakfast"
    And it has a value of "4.0"
    And there is a metric in the database with the name "humalog"
    And it has a datetime of "2014-01-15T12:50:38+00:00"
    And it has a category of "Lunch"
    And it has a value of "5.0"

  Scenario: From specific time to specific time
    When I send a GET request to "metrics/humalog/2014-01-14T00:00:00+00:00/2014-01-15T00:00:00+00:00"
    Then the response status should be "200"
    And the JSON response should have "$.count" with the text "2"
    And the JSON response should have "$.values[0].value" with the text "7.5"
    And the JSON response should have "$.values[0].datetime" with the text "2014-01-14T12:25:30+00:00"
    And the JSON response should have "$.values[0].category" with the text "Lunch"
    And the JSON response should have "$.values[1].value" with the text "6.0"
    And the JSON response should have "$.values[1].datetime" with the text "2014-01-14T18:47:19+00:00"
    And the JSON response should have "$.values[1].category" with the text "Dinner"

  Scenario: From * to specific time
    When I send a GET request to "metrics/humalog/*/2014-01-15T12:00:00+00:00"
    Then the response status should be "200"
    And the JSON response should have "$.count" with the text "3"
    And the JSON response should have "$.values[0].value" with the text "7.5"
    And the JSON response should have "$.values[0].datetime" with the text "2014-01-14T12:25:30+00:00"
    And the JSON response should have "$.values[0].category" with the text "Lunch"
    And the JSON response should have "$.values[1].value" with the text "6.0"
    And the JSON response should have "$.values[1].datetime" with the text "2014-01-14T18:47:19+00:00"
    And the JSON response should have "$.values[1].category" with the text "Dinner"
    And the JSON response should have "$.values[2].value" with the text "4.0"
    And the JSON response should have "$.values[2].datetime" with the text "2014-01-15T07:24:04+00:00"
    And the JSON response should have "$.values[2].category" with the text "Breakfast"

  Scenario: From specific time to *
    When I send a GET request to "metrics/humalog/2014-01-15T06:00:00+00:00/*"
    Then the response status should be "200"
    And the JSON response should have "$.count" with the text "2"
    And the JSON response should have "$.values[0].value" with the text "4.0"
    And the JSON response should have "$.values[0].datetime" with the text "2014-01-15T07:24:04+00:00"
    And the JSON response should have "$.values[0].category" with the text "Breakfast"
    And the JSON response should have "$.values[1].value" with the text "5.0"
    And the JSON response should have "$.values[1].datetime" with the text "2014-01-15T12:50:38+00:00"
    And the JSON response should have "$.values[1].category" with the text "Lunch"

  Scenario: From * to *
    When I send a GET request to "metrics/humalog/*/*"
    Then the response status should be "200"
    And the JSON response should have "$.count" with the text "4"
    And the JSON response should have "$.values[0].value" with the text "7.5"
    And the JSON response should have "$.values[0].datetime" with the text "2014-01-14T12:25:30+00:00"
    And the JSON response should have "$.values[0].category" with the text "Lunch"
    And the JSON response should have "$.values[1].value" with the text "6.0"
    And the JSON response should have "$.values[1].datetime" with the text "2014-01-14T18:47:19+00:00"
    And the JSON response should have "$.values[1].category" with the text "Dinner"
    And the JSON response should have "$.values[2].value" with the text "4.0"
    And the JSON response should have "$.values[2].datetime" with the text "2014-01-15T07:24:04+00:00"
    And the JSON response should have "$.values[2].category" with the text "Breakfast"
    And the JSON response should have "$.values[3].value" with the text "5.0"
    And the JSON response should have "$.values[3].datetime" with the text "2014-01-15T12:50:38+00:00"
    And the JSON response should have "$.values[3].category" with the text "Lunch"

  Scenario: From duration up to specific time
    When I send a GET request to "metrics/humalog/P1D/2014-01-15T19:00:00+00:00"
    Then the response status should be "200"
    And the JSON response should have "$.count" with the text "2"
    And the JSON response should have "$.values[0].value" with the text "4.0"
    And the JSON response should have "$.values[0].datetime" with the text "2014-01-15T07:24:04+00:00"
    And the JSON response should have "$.values[0].category" with the text "Breakfast"
    And the JSON response should have "$.values[1].value" with the text "5.0"
    And the JSON response should have "$.values[1].datetime" with the text "2014-01-15T12:50:38+00:00"
    And the JSON response should have "$.values[1].category" with the text "Lunch"

  Scenario: From specific time for duration
    When I send a GET request to "metrics/humalog/2014-01-15T00:00:00+00:00/PT12H"
    Then the response status should be "200"
    And the JSON response should have "$.count" with the text "1"
    And the JSON response should have "$.values[0].value" with the text "4.0"
    And the JSON response should have "$.values[0].datetime" with the text "2014-01-15T07:24:04+00:00"
    And the JSON response should have "$.values[0].category" with the text "Breakfast"